# Generated by Django 2.2.6 on 2020-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Done', models.BooleanField(default=False)),
                ('DateStamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
