# Generated by Django 2.2.6 on 2020-05-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Details', models.TextField()),
                ('Due', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Todo',
            new_name='DailyTodo',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Duration', models.CharField(max_length=20)),
                ('done', models.BooleanField(default=False)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
            ],
        ),
    ]
