# Generated by Django 2.2.6 on 2020-05-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200507_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytodo',
            name='Description',
        ),
    ]
